language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.2
  - 2.3.0
  - jruby-9.0.0.0
  - jruby-9.0.0.0-20mode
  - jruby-9.0.0.0-21mode

env:
  - ACTIVERECORD_VERSION=4.0.0
  - ACTIVERECORD_VERSION=3.2.0
  - ACTIVERECORD_VERSION=4.1.14
  - ACTIVERECORD_VERSION=4.2.5
  - ACTIVERECORD_VERSION=5.0.0
  - ACTIVERECORD_VERSION=master

matrix:
  exclude:
    - rvm: 2.0.0
      env: ACTIVERECORD_VERSION=master
    - rvm: 2.1.0
      env: ACTIVERECORD_VERSION=master
    - rvm: jruby-9.0.0.0
      env: ACTIVERECORD_VERSION=master
    - rvm: jruby-9.0.0.0-20mode
      env: ACTIVERECORD_VERSION=master
    - rvm: jruby-9.0.0.0-21mode
      env: ACTIVERECORD_VERSION=master
    - rvm: 2.0.0
      env: ACTIVERECORD_VERSION=5.0.0.beta1
    - rvm: 2.1.0
      env: ACTIVERECORD_VERSION=5.0.0.beta1
    - rvm: jruby-9.0.0.0
      env: ACTIVERECORD_VERSION=5.0.0.beta1
    - rvm: jruby-9.0.0.0-20mode
      env: ACTIVERECORD_VERSION=5.0.0.beta1
    - rvm: jruby-9.0.0.0-21mode
      env: ACTIVERECORD_VERSION=5.0.0.beta1
